spring:
  datasource:
    url: jdbc:h2:mem:blog;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: ilwoo
    password: qkrdlfdn1!

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: embedded